interline-io/calact-network-analysis-tool

components/cal/map-viewer-ts.vue
components/cal/map.vue
components/cal/scenario.vue

Basic support for route filtering.
Routes not selected are shown in gray.
Resolves #27

Route filters

---

components/constants.ts

Change route labels

---

pages/tne.vue

Fix cancel button on modal dialog

---

components/cal/filter.vue

Filter agencies by input text

---

components/cal/filter.vue
components/cal/map.vue
components/cal/scenario.vue

And set limit to 100 to prevent timeouts
Resolves #36

Improve route pagination

---

components/cal/filter.vue
components/cal/scenario.vue
pages/tne.vue

Resolves #37 
Also improves loading queue, resolves #30

Use start date

---

components/cal/map-viewer-ts.vue
components/cal/map.vue
components/cal/report.vue
pages/tne.vue

re: #43 
Work in Progress on the Reports component

Initial sketch of Reports Component

---

package.json
yarn.lock

Upgrade nuxt to 3.16

---

components/cal/csv-download.vue
components/cal/report.vue
package.json
yarn.lock

Initial work on CSV download

---

components/cal/filter.vue
components/cal/query.vue
components/constants.ts
components/datetime.ts
components/geom.ts
pages/tne.vue

This adds functionality for timeframe filtering re: #45

Timeframes filtering controls

---

components/cal/filter.vue
components/cal/map-viewer-ts.vue
components/cal/report.vue
components/cal/scenario.vue
components/constants.ts
components/departure.ts
components/stop.ts
pages/tne.vue

Add visit counts / average / by dow / by date to stops
Add frequency value to routes / by dow / by date to routes
Related to #45 and #46

Add frequency values for stops

---

components/cal/legend.vue
components/cal/map.vue
components/constants.ts
pages/tne.vue

WIP on making the legend and map style respond to the Data Display options 
(re: #52)
- Moved legend code from `map.vue` into its own `legend.vue` component
- Adjusted styling for various data reporting formats
- Updated CSS for different map style legend items (circle, line, marker)

Dynamic legend and map styling

---

components/cal/map-share.vue
components/cal/map.vue
components/cal/report.vue

Add stop and route csv to map share tab

---

components/cal/query.vue

revise help text

---

components/cal/filter.vue
components/constants.ts

clarify which filters and options are disabled because they're planned/future functionality

---

components/cal/query.vue
components/cal/scenario.vue
components/main-header.vue
composables/useDebugMenu.ts
eslint.config.mjs
pages/tne.vue

Debug menu composable

---

components/agency.ts
components/cal/map-share.vue
components/cal/map.vue
components/cal/report.vue
components/cal/scenario.vue
pages/tne.vue

Also make agency report more consistent
Resolves #91

Download agencies

---

components/cal/report.vue

based on some questions and feedback that came up on call with PMs

improve help text & styling on the Report page

---

components/cal/legend.vue
components/cal/map-viewer-ts.vue
components/cal/map.vue

- that was being confused with light rail mode
- also improvements legend
closes https://github.com/interline-io/calact-network-analysis-tool/issues/140

fallback default styling for bus stop will now be gray, instead of red

---

components/analysis/picker.vue
components/analysis/wsdot-stops-routes.vue
components/analysis/wsdot-viewer.vue
components/analysis/wsdot.vue
components/cal/datagrid.vue
components/cal/map-viewer-ts.vue
src/reports/wsdot.ts

- move the stop buffer radius control to initial Analysis form for #135
- stub out start of #143
- add explanatory text
- UI styling improvements
- cancel/back button

UI improvements for WSDOT analyses

---

components/analysis/wsdot-viewer.vue

WSDOT analysis: fix stops mistakely assigned to nights level

---

components/analysis/wsdot-viewer.vue
components/cal/datagrid.vue
components/cal/geojson-download.vue

closes https://github.com/interline-io/calact-network-analysis-tool/issues/175

download geojson for WSDOT Frequent Transit Service Study

---

components/analysis/wsdot-viewer.vue
src/analysis/wsdot/index.ts
src/core/geom.ts
src/scenario/scenario.ts

closes https://github.com/interline-io/calact-network-analysis-tool/issues/174

Use bbox area for population counts
